# Generated by Django 4.2 on 2023-10-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='選手名')),
                ('gender', models.CharField(max_length=10, verbose_name='性別')),
                ('grade', models.CharField(max_length=10, verbose_name='学年')),
            ],
            options={
                'db_table': 'athlete',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('discipline', models.CharField(max_length=100, verbose_name='種目')),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('division', models.CharField(max_length=100, verbose_name='区分')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('event', models.CharField(max_length=100, verbose_name='大会名')),
                ('date', models.DateField(verbose_name='日付')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(max_length=100, verbose_name='ラウンド')),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Event_records',
            fields=[
                ('record', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='記録')),
                ('wind', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='風速')),
                ('heat', models.CharField(max_length=10, verbose_name='組')),
                ('place', models.CharField(max_length=100, verbose_name='順位')),
                ('event_records_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logmaneapp.athlete')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logmaneapp.discipline')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logmaneapp.division')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logmaneapp.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logmaneapp.stage')),
            ],
            options={
                'db_table': 'event_records',
            },
        ),
        migrations.CreateModel(
            name='Athlete_records',
            fields=[
                ('personal_best', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='自己ベスト')),
                ('university_best', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='大学ベスト')),
                ('valid_record', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='有効記録')),
                ('athlete_records_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logmaneapp.athlete')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logmaneapp.discipline')),
            ],
            options={
                'db_table': 'athlete_records',
            },
        ),
        migrations.AddConstraint(
            model_name='event_records',
            constraint=models.UniqueConstraint(fields=('athlete_id', 'event', 'discipline', 'stage'), name='event_records_unique'),
        ),
        migrations.AddConstraint(
            model_name='athlete_records',
            constraint=models.UniqueConstraint(fields=('athlete_id', 'discipline'), name='athlete_records_unique'),
        ),
    ]
