# Generated by Django 4.2 on 2023-10-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmaneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female,', '女'), ('other', 'その他')], max_length=10, verbose_name='性別'),
        ),
    ]
