# Generated by Django 4.2 on 2023-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmaneapp', '0002_alter_athlete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.CharField(max_length=10, null=True, verbose_name='パート'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='性別'),
        ),
    ]
