# Generated by Django 4.2 on 2023-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logmaneapp', '0003_athlete_group_alter_athlete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='athlete_records',
            name='athlete_records_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='division_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event_records',
            name='event_records_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
